@startuml

object Table {
    table_name
    table_hash
}

object Row {
    row_hash
}

object ColValue

database "Database" as DB1 {
}

database "Database" as DB2 {
}

object "TableSummary" as TS1 {
    snapshot_id
    table_name
    table_hash
}

DB1 .r..> "*" Table : dump
Table -d-> "*" Row
Row -d-> "*" ColValue

Table -u-> TS1
TS1 .u.> DB2 : save

object Snapshot {
    snapshot_id
}

DB2 .d.> Snapshot : load

object "TableSummary" as TS2 {
    snapshot_id
    table_name
    table_hash
}

Snapshot -d-> "*" TS2
TS2 .l.> Table : load


@enduml