@startuml

'
' database
'

database "Database" as DB1 {
}

database "Database" as DB2 {
}

'
' dump
'

object "TableSummary" as TS1 {
    snapshot_id
    table_name
    hash
    primary_col_name
    col_names
}

object "Row" as R1 {
    primary_value
    hash
}

'
' load
'

object "TableSummary" as TS2 {
    snapshot_id
    table_name
    hash
    primary_col_name
    col_names
}

object Table {
    name
    primary_col_name
    col_names
}

object "Row" as R2 {
    primary_value
    hash
}

object ColValue

'
' relation
'

' dump
DB1 .d.> TS1 : dump
DB1 .d.> R1 : dump
TS1 .d.> DB2 : save
R1 .d.> DB2 : save

' load
DB2 .r.> TS2 : load
TS2 .d.> Table : load
Table -d-> "*" R2
R2 -d-> "*" ColValue

@enduml